name = "After Dark"
license = "WTFPL"
licenselink = "https://choosealicense.com/licenses/wtfpl/"
description = "A deceptively simple hacker theme for Hugo."
homepage = "https://git.habd.as/comfusion/after-dark/"
tags = [
  "personal",
  "minimal",
  "responsive",
  "accessible",
  "search"
]
features = [
  "Quick Installer",
  "Module System",
  "Theme Variants",
  "Lazy Loading",
  "Social Engagement",
  "Search Optimization",
  "Post Images",
  "Fuzzy Search",
  "Personalization",
  "Content Reuse",
  "Related Content",
  "Table of Contents",
  "Modification Dating",
  "Syntax Highlighting",
  "Taxonomy Pages",
  "Error Page",
  "Pagination",
  "Reading Time",
  "Post Bylines"
]
min_version = 0.44

[author]
  name = "Josh Habdas"
  homepage = "https://habd.as"
